In [15]:
#import statements
from gensim import corpora, models, similarities
from time import time
from nltk.tokenize import sent_tokenize,word_tokenize,regexp_tokenize

In [2]:
#loading data 
docs = ['Book_1','Book_2','Book_3']
doc_list = []
for i in docs:
    doc_list.append(open(i,'r').read().split())
    


In [23]:
len(doc_list[3])

IndexError: list index out of range

In [4]:
# creating dictionary (giving index of each unique word)
dictionary = corpora.Dictionary(doc_list)
dictionary.save('/tmp/harry.dict') # store the dictionary, for future reference
print(len(dictionary))

26888


In [5]:
# compile corpus (vectors number of times each elements appears)
raw_corpus = [dictionary.doc2bow(t) for t in doc_list]
print("Then convert convert tokenized documents to vectors: %s"% type(raw_corpus))
corpora.MmCorpus.serialize('/tmp/harry.mm', raw_corpus) # store to disk
print("Save the vectorized corpus as a .mm file")

Then convert convert tokenized documents to vectors: <class 'list'>
Save the vectorized corpus as a .mm file


In [6]:
dictionary = corpora.Dictionary.load('/tmp/harry.dict')

In [7]:
corpus = corpora.MmCorpus('/tmp/harry.mm')

In [8]:
#computing idfs of different words
tfidf = models.TfidfModel(corpus)

In [16]:
tfidf.idfs

{0: 0.0,
 1: 0.0,
 2: 1.5849625007211563,
 3: 1.5849625007211563,
 4: 0.5849625007211562,
 5: 1.5849625007211563,
 6: 1.5849625007211563,
 7: 0.0,
 8: 0.5849625007211562,
 9: 1.5849625007211563,
 10: 1.5849625007211563,
 11: 0.5849625007211562,
 12: 0.5849625007211562,
 13: 0.0,
 14: 0.0,
 15: 0.5849625007211562,
 16: 1.5849625007211563,
 17: 0.5849625007211562,
 18: 1.5849625007211563,
 19: 0.0,
 20: 0.0,
 21: 0.0,
 22: 0.5849625007211562,
 23: 0.5849625007211562,
 24: 0.0,
 25: 1.5849625007211563,
 26: 0.0,
 27: 0.0,
 28: 0.0,
 29: 0.0,
 30: 0.5849625007211562,
 31: 0.0,
 32: 1.5849625007211563,
 33: 1.5849625007211563,
 34: 0.5849625007211562,
 35: 0.0,
 36: 0.0,
 37: 1.5849625007211563,
 38: 1.5849625007211563,
 39: 1.5849625007211563,
 40: 0.0,
 41: 0.5849625007211562,
 42: 1.5849625007211563,
 43: 0.0,
 44: 0.0,
 45: 1.5849625007211563,
 46: 0.0,
 47: 1.5849625007211563,
 48: 0.5849625007211562,
 49: 0.0,
 50: 0.0,
 51: 1.5849625007211563,
 52: 0.5849625007211562,
 53: 0.0,
 54: 

In [9]:
# transforming the corpus 
corpus_tfidf = tfidf[corpus]

In [10]:
# computing doc to doc similarity
index = similarities.MatrixSimilarity(tfidf[corpus])
index.save('/tmp/harry.index')
index = similarities.MatrixSimilarity.load('/tmp/harry.index')
sims = index[corpus_tfidf]
print("We get a similarity matrix for all documents in the corpus %s"% type(sims))
print(sims)


We get a similarity matrix for all documents in the corpus <class 'numpy.ndarray'>
[[ 1.00000083  0.01297695  0.02071972]
 [ 0.01297695  0.99999702  0.01274075]
 [ 0.02071972  0.01274075  1.00000048]]


In [11]:
#function to get similarity og given sentense to documents
def query_of_similarity(t):
    #text = regex_token(t)
    s = sent_tokenize(t)
    text = []
    for sent in s:
        text.append(word_tokenize(sent))
    dictionary2 = corpora.Dictionary(text)
    dictionary2.save('/tmp/query.dict') # store the dictionary, for future reference
    raw_corpus2 = [dictionary.doc2bow(t) for t in text]
    corpora.MmCorpus.serialize('/tmp/rawcorpus2.mm', raw_corpus2) # store to disk
    dictionary2 = corpora.Dictionary.load('/tmp/query.dict')
    corpus2 = corpora.MmCorpus('/tmp/rawcorpus2.mm')
    r = index.get_similarities(tfidf[corpus2])
    print(r)

    


In [12]:
query_of_similarity("""At half past eight, Mr. Dursley picked up his briefcase, pecked Mrs.
Dursley on the cheek, and tried to kiss Dudley good-bye but missed,
because Dudley was now having a tantrum and throwing his cereal at the
walls. Little tyke, chortled Mr. Dursley as he left the house. He got
into his car and backed out of number four's drive.""")

[[ 0.019132    0.06812366  0.00527635]
 [ 0.01524487  0.09758063  0.00056097]
 [ 0.00269059  0.12914188  0.00181712]]


In [13]:
#function to get similarity of given sentense to documents
def query_of_similarity1(t):
    text = (word_tokenize(t))
    dictionary2 = corpora.Dictionary([text])
    dictionary2.save('/tmp/query.dict') 
    raw_corpus2 = [dictionary.doc2bow(t) for t in [text]]
    corpora.MmCorpus.serialize('/tmp/rawcorpus2.mm', raw_corpus2) 
    dictionary2 = corpora.Dictionary.load('/tmp/query.dict')
    corpus2 = corpora.MmCorpus('/tmp/rawcorpus2.mm')
    r = index.get_similarities(tfidf[corpus2])
    print(r)

    


In [14]:
query_of_similarity1("""At half past eight, Mr. Dursley picked up his briefcase, pecked Mrs.
Dursley on the cheek, and tried to kiss Dudley good-bye but missed,
because Dudley was now having a tantrum and throwing his cereal at the
walls. Little tyke, chortled Mr. Dursley as he left the house. He got
into his car and backed out of number four's drive.""")

[[ 0.02228636  0.14678901  0.0047468 ]]
